#!/usr/bin/env python3
"""Generate the cover's two decorative layers.

Run from the repository root:

    python3 structure-analysis/gen_fx.py --seed 5

Writes layouts/_partials/fx/pixels.html and layouts/_partials/fx/spark.html.
Both sit in the same registered box as the chain traces, so every position here
is a plain percentage of the 2172x724 source and lands on the artwork's own
cell grid at any viewport width.

pixels — cells surfacing and going out again, at the artwork's pitch and in the
colour that cell already is. A full grid would be ~27,000 cells with a couple
of dozen alight at any instant, so only the candidates are emitted; on screen
the result is identical. Positions are drawn from cells the artwork itself
leaves dark, because a cell that surfaces where a structure already sits is
invisible.

spark — a streak crossing the band and bursting into fragments where it lands.
The streak is not a smooth gradient: it is a repeating-linear-gradient on the
cell pitch, so it reads as a trail of squares rather than a drawn line. That
was the whole objection to the first attempt at this — a smooth streak beside
pixel art looks like something laid on top of the picture instead of part of it.

Colours come from the artwork on both counts. Every colour in it has R = 0, and
the layers composite with `screen`, so nothing can land on a hue the picture
does not already contain.
"""

import argparse
import math
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from detect import PITCH, SQUARE, SRC, cell_grid
from PIL import Image

PIXELS = "layouts/_partials/fx/pixels.html"
SPARK = "layouts/_partials/fx/spark.html"

N_PIXELS = 90
N_SPARKS = 5
LIFT = 2.6          # dark cells need much more than a structure cell does
FLOOR = (40, 150, 190)   # nothing dimmer than this, or a surfacing cell is invisible


def sample(im, ox, oy, r, c):
    """Mean colour of one cell, lifted until it can be seen against the field."""
    box = (ox + c * PITCH + 1, oy + r * PITCH + 1,
           ox + c * PITCH + PITCH - 1, oy + r * PITCH + PITCH - 1)
    px = list(im.crop(box).getdata())
    col = [sum(q[i] for q in px) / len(px) * LIFT for i in range(3)]
    # Keep the artwork's hue but guarantee a floor, then hold R low: the cover
    # is pure cyan-to-blue and a warm cell would read as a foreign object.
    col = [max(col[i], FLOOR[i]) for i in range(3)]
    col[0] = min(col[0], 90)
    return tuple(min(255, int(v)) for v in col)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=5)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    im = Image.open(SRC).convert("RGB")
    W, H = im.size
    grid, rows, cols, ox, oy = cell_grid(im)

    # Percentages of the source, so a cell is square inside a 3:1 box.
    pw, ph = SQUARE / W * 100, SQUARE / H * 100

    # ---- pixels ---------------------------------------------------------
    # Only cells the artwork leaves dark; a structure cell would swallow them.
    dark = [(r, c) for r in range(rows) for c in range(cols) if grid[r][c] < 26]
    rng.shuffle(dark)
    chosen, seen = [], set()
    for r, c in dark:
        if len(chosen) >= N_PIXELS:
            break
        if any(abs(r - r2) < 3 and abs(c - c2) < 3 for r2, c2 in seen):
            continue          # no clumping: they should read as scattered
        seen.add((r, c))
        chosen.append((r, c))

    cycles = [7, 8, 9, 11, 12, 13, 14, 16, 17, 19]
    rowsout = []
    for i, (r, c) in enumerate(chosen):
        col = sample(im, ox, oy, r, c)
        d = cycles[i % len(cycles)]
        rowsout.append(
            '  <i class="px" style="--x:{:.3f}%;--y:{:.3f}%;--w:{:.3f}%;'
            '--h:{:.3f}%;--c:rgb({},{},{});--d:{}s;--dl:-{:.1f}s"></i>'.format(
                (ox + c * PITCH) / W * 100, (oy + r * PITCH) / H * 100, pw, ph,
                col[0], col[1], col[2], d, rng.uniform(0, d)))
    open(PIXELS, "w").write(
        '{{- /*\n'
        '  Pixel surfacing. Generated by structure-analysis/gen_fx.py (seed %d).\n'
        '\n'
        '  Cells on the artwork\'s own 7px pitch, each in the colour that cell\n'
        '  already is, lifted until it reads against the field. Only cells the\n'
        '  artwork leaves dark are used — one surfacing inside a structure is\n'
        '  invisible — and no two sit within three cells of each other, so they\n'
        '  scatter instead of clumping.\n'
        '\n'
        '  Tunables live on `.fx-px` in css/main.css (§ cover).\n'
        '*/ -}}\n'
        '<div class="fx-px fx-reg" aria-hidden="true">\n%s\n</div>\n'
        % (args.seed, "\n".join(rowsout)))
    print(f"  pixels: {len(chosen)} cells -> {PIXELS}")

    # ---- sparks ---------------------------------------------------------
    # Everything inside a spark is sized in percentages, so its container must
    # be the full artwork rect: a percentage inside a zero-size positioned box
    # resolves to zero, and the first version of this drew nothing at all.
    # `translate()` percentages are of the element's own box, not the parent's,
    # so travel and fragment reach are emitted in multiples of that instead.
    cw, ch = PITCH / W * 100, PITCH / H * 100
    sparks = []
    prime = [19, 23, 29, 31, 37, 41, 43]
    for i in range(N_SPARKS):
        ix = rng.uniform(0.14, 0.86) * W          # impact point, source px
        iy = rng.uniform(0.58, 0.90) * H          # the clear lower band
        ang = rng.uniform(20, 34)                 # descending, right to left
        travel = rng.uniform(0.22, 0.40) * W
        tail = rng.uniform(9, 16) * PITCH
        dur = prime[i % len(prime)]
        frags = ['    <i class="fl"></i>']    # the flash at the point of impact
        for _ in range(rng.randint(11, 16)):
            a = math.radians(rng.uniform(0, 360))
            reach = rng.uniform(2.5, 11.0)        # in cells; a few throw far
            big = rng.random() < 0.3              # mixed sizes read as debris
            frags.append(
                '    <i class="sf{}" style="--fx:{:.0f}%;--fy:{:.0f}%;--fd:{:.2f}s">'
                '</i>'.format(" big" if big else "",
                              math.cos(a) * reach * 100,
                              math.sin(a) * reach * 100,
                              rng.uniform(0, 0.10)))
        sparks.append(
            '  <div class="sp" style="--ix:{:.3f}%;--iy:{:.3f}%;--sx:{:.3f}%;'
            '--ang:{:.1f}deg;--len:{:.3f}%;--back:{:.0f}%;--cw:{:.4f}%;'
            '--ch:{:.4f}%;--d:{}s;--dl:-{:.1f}s">\n'
            '    <i class="st"></i>\n{}\n  </div>'.format(
                ix / W * 100, iy / H * 100, (ix - tail) / W * 100, ang,
                tail / W * 100, travel / tail * 100, cw, ch, dur,
                rng.uniform(0, dur), "\n".join(frags)))
    open(SPARK, "w").write(
        '{{- /*\n'
        '  Sparks. Generated by structure-analysis/gen_fx.py (seed %d).\n'
        '\n'
        '  A streak crosses the band and bursts into fragments where it lands.\n'
        '  The streak is a repeating-linear-gradient on the cell pitch, not a\n'
        '  smooth gradient, so it reads as a trail of squares — a drawn line\n'
        '  beside pixel art looks like something laid over the picture rather\n'
        '  than part of it.\n'
        '\n'
        '  Sizes are percentages of the artwork, so each spark spans the whole\n'
        '  registered box rather than sitting at a point: a percentage inside a\n'
        '  zero-size positioned box resolves to zero, which is why the first\n'
        '  version of this drew nothing. Travel and fragment reach are instead\n'
        '  multiples of the element\'s own box, which is what translate() takes.\n'
        '\n'
        '  Tunables live on `.fx-spark` in css/main.css (§ cover).\n'
        '*/ -}}\n'
        '<div class="fx-spark fx-reg" aria-hidden="true">\n%s\n</div>\n'
        % (args.seed, "\n".join(sparks)))
    print(f"  sparks: {N_SPARKS} -> {SPARK}")
    print(f"  bytes: {os.path.getsize(PIXELS) + os.path.getsize(SPARK):,d}")


if __name__ == "__main__":
    main()
