#!/usr/bin/env python3
"""Generate the cover's in-situ chain traces.

Exports 1-bit silhouettes to assets/images/bg/traces/ and writes the partial
layouts/_partials/fx/chain.html. Run from the repository root:

    python3 structure-analysis/gen_traces.py --seed 3

The shapes are the artwork's own. Each silhouette is laid back over the cells it
was cut from, so nothing is duplicated and nothing is invented; what animates is
a light travelling along that structure's backbone. Detection lives in
detect.py — see its notes for why the threshold and the width-based separation
are what they are.

Sizing and rhythm are derived, not guessed:

* Each stroke is sized from its own structure's 95th-percentile cell, so one
  outlying cell in a corner cannot demand a stroke half the chain's length.
* Each period is proportional to its chain's length, so the light travels at the
  same ~7.5 cells/s along all of them, from one keyframe set.
* Periods are distinct primes, so the group never falls into a rhythm.
"""

import argparse
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from detect import (CELLS_PER_SEC, DRAW_FRACTION, MIN_CELLS, PITCH, PRIMES,
                    SRC, cell_grid, centreline, classify, elements,
                    silhouette, stroke_cells, MAX_STROKE, MAX_STROKE_RATIO,
                    NARROW_STROKE)
from PIL import Image

OUTDIR = "assets/images/bg/traces"
PARTIAL = "layouts/_partials/fx/chain.html"

HEAD = '''{{{{- /*
  In-situ chain traces. Generated by structure-analysis/gen_traces.py (seed {seed}).

  The shapes are the artwork's own. The cover is quantised back onto its 7px
  cell grid, flood-filled into {ncomp} connected components, and {n} of them are
  exported as 1-bit silhouettes. Each is laid back exactly over the structure it
  was cut from, so nothing is duplicated and nothing is invented — the picture
  simply lights up along one chain at a time, from the head of that chain.

  Each silhouette masks a stroke drawn along the structure's own centreline
  (found by BFS through the cell adjacency), and `pathLength="1"` normalises
  every chain, so one keyframe set drives them all. Periods are proportional to
  chain length, which makes the light travel at the same speed along each, and
  are distinct primes, so the group never falls into a rhythm.

  Registration lives in css/main.css (§ cover): `.fx-chain` is laid out as the
  artwork's rendered rectangle rather than as the band, so every child is placed
  in plain % of the {sw}x{sh} source and stays exact at any viewport width.

  Tunables live on `.fx-chain` in css/main.css (§ cover).
*/ -}}}}
<div class="fx-chain" aria-hidden="true">'''

SVG = '''
  {{{{- with resources.Get "images/bg/traces/{name}.png" }}}}
  <svg class="cm" viewBox="0 0 {w} {h}" preserveAspectRatio="none"
    aria-hidden="true" focusable="false"
    style="--x: {x:.3f}%; --y: {y:.3f}%; --w: {pw:.3f}%; --h: {ph:.3f}%; --d: {d}s; --dl: -{dl}s">
    {{{{- /* The reveal is the mask and the artwork is the paint, not the other
           way round: a stroked path would paint every cell one flat colour. */}}}}
    <mask id="tc{i}" maskUnits="userSpaceOnUse" x="0" y="0" width="{w}" height="{h}">
      <path class="cm-run" d="{chain}" pathLength="1" fill="none" stroke="#fff"
        stroke-width="{sw}" stroke-linecap="butt" stroke-linejoin="round" />
    </mask>
    <g mask="url(#tc{i})">
      <image href="{{{{ .RelPermalink }}}}" width="{w}" height="{h}" />
      {{{{- with resources.Get "images/bg/traces/{name}-deep.png" }}}}
      <image class="cm-deep" href="{{{{ .RelPermalink }}}}" width="{w}" height="{h}" />
      {{{{- end }}}}
    </g>
  </svg>
  {{{{- end }}}}'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=3)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    im = Image.open(SRC).convert("RGB")
    # The hover artwork is a warm palette; sampling it too means the traces
    # follow whichever image is showing instead of being hue-rotated into a
    # colour neither picture contains.
    deep = Image.open(SRC.replace(".png", "-deep.png")).convert("RGB")
    SW, SH = im.size
    grid, rows, cols, ox, oy = cell_grid(im)
    comps = elements(grid, rows, cols)

    kinds = {}
    ok = []

    def consider(cs):
        if len(cs) < MIN_CELLS:
            return False
        line, chain_cells = centreline(cs)
        if len(line) < 3:
            return False
        k = classify(cs, line, chain_cells)
        if k not in ("helix", "strand", "turn"):   # loops are not lit
            return False
        sw = stroke_cells(cs, line)
        if sw <= MAX_STROKE and (sw <= NARROW_STROKE
                                 or sw / max(1, chain_cells) <= MAX_STROKE_RATIO):
            ok.append((cs, line, chain_cells, k, sw))
            return True
        return False

    for cs in comps:
        line, chain_cells = centreline(cs)
        k = classify(cs, line, chain_cells) if len(line) >= 2 else "fragment"
        kinds[k] = kinds.get(k, 0) + len(cs)
        consider(cs)
    lit = sum(len(c) for c in comps)
    print(f"{len(comps)} components, {lit} lit cells")
    for k in ("helix", "strand", "turn", "loop", "fragment"):
        print(f"   {k:9s} {kinds.get(k, 0):5d} cells  {kinds.get(k, 0) / lit:5.1%}")
    # Assign periods shortest-chain first, so each structure gets the prime
    # nearest its own ideal and the light keeps the same speed on all of them.
    chosen = sorted(ok, key=lambda t: t[2])
    n = len(chosen)
    print(f"animating {n} structures = "
          f"{sum(len(t[0]) for t in chosen) / lit:.0%} of the lit area")

    os.makedirs(OUTDIR, exist_ok=True)
    for f in os.listdir(OUTDIR):
        os.remove(os.path.join(OUTDIR, f))

    parts = [HEAD.format(seed=args.seed, ncomp=len(comps), n=n, sw=SW, sh=SH)]
    total = 0
    for i, (cs, line, chain_cells, kind, sw_cells) in enumerate(chosen):
        name = f"s{i}"
        w, h, r0, c0 = silhouette(cs, im, ox, oy, os.path.join(OUTDIR, name + ".png"))
        silhouette(cs, deep, ox, oy, os.path.join(OUTDIR, name + "-deep.png"))
        total += os.path.getsize(os.path.join(OUTDIR, name + ".png"))
        # Period from chain length, so every trace travels at the same speed.
        want = chain_cells / CELLS_PER_SEC / DRAW_FRACTION
        # Nearest prime, and repeats are allowed. Forcing 36 distinct periods
        # pushed the long chains up to 170s — three minutes between showings,
        # and the light crawling at 4.9 cells/s instead of 7.5. Two structures
        # sharing a period is invisible anyway: their phases differ.
        period = min(PRIMES, key=lambda q: (abs(q - want), q))
        d = "M" + "L".join(
            f"{(x - c0) * PITCH + PITCH // 2:.0f} {(y - r0) * PITCH + PITCH // 2:.0f}"
            for x, y in line)
        parts.append(SVG.format(
            i=i, name=name, w=w * PITCH, h=h * PITCH,
            x=(ox + c0 * PITCH) / SW * 100, y=(oy + r0 * PITCH) / SH * 100,
            pw=w * PITCH / SW * 100, ph=h * PITCH / SH * 100,
            d=period, dl=rng.randrange(period), chain=d,
            sw=round(sw_cells * PITCH)))
        print(f"  {name:4s} {kind:7s} {len(cs):4d} cells  chain {chain_cells:3d}  "
              f"stroke {sw_cells:4.1f}c  period {period:3d}s  "
              f"draw {period * DRAW_FRACTION:4.1f}s  "
              f"({chain_cells / (period * DRAW_FRACTION):4.1f} cells/s)")
    parts.append("\n</div>\n")
    open(PARTIAL, "w").write("".join(parts))
    print(f"wrote {PARTIAL} ({len(''.join(parts))} bytes) "
          f"+ {n} silhouettes ({total} bytes)")


if __name__ == "__main__":
    main()
