#!/usr/bin/env python3
"""Generate the cover's in-situ chain traces.

Exports 1-bit silhouettes to assets/images/bg/traces/ and writes the partial
layouts/_partials/fx/chain.html. Run from the repository root:

    python3 structure-analysis/gen_traces.py --seed 3

The shapes are the artwork's own. Each silhouette is laid back over the cells it
was cut from, so nothing is duplicated and nothing is invented; what animates is
a light travelling along that structure's backbone. Detection lives in
detect.py — see its notes for why the threshold and the width-based separation
are what they are.

Sizing and rhythm are derived, not guessed:

* Each stroke is sized from its own structure's 95th-percentile cell, so one
  outlying cell in a corner cannot demand a stroke half the chain's length.
* Each period is proportional to its chain's length, so the light travels at the
  same ~7.5 cells/s along all of them, from one keyframe set.
* Periods are distinct primes, so the group never falls into a rhythm.
"""

import argparse
import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from detect import (CELLS_PER_SEC, DRAW_FRACTION, MIN_CELLS, PITCH, PRIMES,
                    SRC, cell_grid, centreline, classify, elements,
                    silhouette, stroke_cells, MAX_STROKE, MAX_STROKE_RATIO,
                    NARROW_STROKE)
from PIL import Image

OUTDIR = "assets/images/bg/traces"
GROUPS = os.path.join(os.path.dirname(os.path.abspath(__file__)), "groups.json")
PARTIAL = "layouts/_partials/fx/chain.html"

HEAD = '''{{{{- /*
  In-situ chain traces. Generated by structure-analysis/gen_traces.py (seed {seed}).

  The shapes are the artwork's own. The cover is quantised back onto its 7px
  cell grid, flood-filled into {ncomp} connected components, and {n} of them are
  exported as 1-bit silhouettes. Each is laid back exactly over the structure it
  was cut from, so nothing is duplicated and nothing is invented — the picture
  simply lights up along one chain at a time, from the head of that chain.

  Each silhouette masks a stroke drawn along the structure's own centreline
  (found by BFS through the cell adjacency), and `pathLength="1"` normalises
  every chain, so one keyframe set drives them all. Periods are proportional to
  chain length, which makes the light travel at the same speed along each, and
  are distinct primes, so the group never falls into a rhythm.

  Registration lives in css/main.css (§ cover): `.fx-chain` is laid out as the
  artwork's rendered rectangle rather than as the band, so every child is placed
  in plain % of the {sw}x{sh} source and stays exact at any viewport width.

  Tunables live on `.fx-chain` in css/main.css (§ cover).
*/ -}}}}
<div class="fx-chain" aria-hidden="true">'''

SVG = '''
  {{{{- with resources.Get "images/bg/traces/{name}.png" }}}}
  <svg class="cm" viewBox="0 0 {w} {h}" preserveAspectRatio="none"
    aria-hidden="true" focusable="false"
    style="--x: {x:.3f}%; --y: {y:.3f}%; --w: {pw:.3f}%; --h: {ph:.3f}%; --d: {d}s; --dl: -{dl}s">
    {{{{- /* The reveal is the mask and the artwork is the paint, not the other
           way round: a stroked path would paint every cell one flat colour. */}}}}
    <mask id="tc{i}" maskUnits="userSpaceOnUse" x="0" y="0" width="{w}" height="{h}">
      <path class="cm-run" d="{chain}" pathLength="1" fill="none" stroke="#fff"
        stroke-width="{sw}" stroke-linecap="butt" stroke-linejoin="round" />
    </mask>
    <g mask="url(#tc{i})">
      <image href="{{{{ .RelPermalink }}}}" width="{w}" height="{h}" />
      {{{{- with resources.Get "images/bg/traces/{name}-deep.png" }}}}
      <image class="cm-deep" href="{{{{ .RelPermalink }}}}" width="{w}" height="{h}" />
      {{{{- end }}}}
    </g>
  </svg>
  {{{{- end }}}}'''


def join_chain(members):
    """One chain from several elements, in the order they were listed.

    Which elements belong to the same chain is not recoverable from the pixels:
    adjacency does not separate them (elements one cell apart are as often in
    different chains as the same one), and neither does the shape of the merged
    result. It is read off the picture by eye and kept in groups.json, whose
    order is also the chain's direction — so each element's own path is flipped
    if need be to carry on from where the last one ended.
    """
    cells, path = [], []
    for cs, line in members:
        cells += cs
        if path:
            a = math.dist(path[-1], line[0])
            b = math.dist(path[-1], line[-1])
            if b < a:
                line = line[::-1]
            # Skeleton endpoints stop short of each other, leaving up to eight
            # cells between one element and the next. Bridged at one cell a
            # step, so the light crosses the join at the speed it travels
            # everywhere else instead of jumping it.
            gap = math.dist(path[-1], line[0])
            if gap > 1.5:
                x0, y0 = path[-1]
                x1, y1 = line[0]
                for k in range(1, int(gap)):
                    t = k / gap
                    path.append((x0 + (x1 - x0) * t, y0 + (y1 - y0) * t))
        elif len(members) > 1:
            # Start at whichever end is further from the next element.
            nxt = members[1][1][0]
            if math.dist(line[0], nxt) < math.dist(line[-1], nxt):
                line = line[::-1]
        path += line
    return sorted(set(cells)), path


def load_groups(picked):
    """Fold the hand-made groupings into `picked`, in their listed order."""
    if not os.path.exists(GROUPS):
        return picked
    chains = json.load(open(GROUPS))["chains"]
    owner, taken = {}, set()
    for gi, chain in enumerate(chains):
        for anchor in chain:
            a = tuple(anchor)
            for i, e in enumerate(picked):
                if a in set(e["cells"]):
                    owner.setdefault((gi, tuple(anchor)), i)
                    taken.add(i)
                    break
    out = [e for i, e in enumerate(picked) if i not in taken]
    for gi, chain in enumerate(chains):
        seq, seen = [], set()
        for anchor in chain:
            i = owner.get((gi, tuple(anchor)))
            if i is not None and i not in seen:
                seen.add(i)
                seq.append(picked[i])
        if len(seq) < 2:
            out += seq
            continue
        cells, path = join_chain([(e["cells"], e["line"]) for e in seq])
        out.append({"cells": cells, "line": path, "chain": len(path) - 1,
                    "kind": max(seq, key=lambda e: len(e["cells"]))["kind"],
                    "stroke": max(e["stroke"] for e in seq)})
        print(f"  chain of {len(seq)}: {sum(len(e['cells']) for e in seq)} cells, "
              f"path {len(path) - 1}")
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--seed", type=int, default=3)
    args = ap.parse_args()
    rng = random.Random(args.seed)

    im = Image.open(SRC).convert("RGB")
    # The hover artwork is a warm palette; sampling it too means the traces
    # follow whichever image is showing instead of being hue-rotated into a
    # colour neither picture contains.
    deep = Image.open(SRC.replace(".png", "-deep.png")).convert("RGB")
    SW, SH = im.size
    grid, rows, cols, ox, oy = cell_grid(im)
    comps = elements(grid, rows, cols)

    kinds = {}
    ok = []

    def consider(cs):
        if len(cs) < MIN_CELLS:
            return False
        line, chain_cells = centreline(cs)
        if len(line) < 3:
            return False
        k = classify(cs, line, chain_cells)
        if k not in ("helix", "strand", "turn"):   # loops are not lit
            return False
        sw = stroke_cells(cs, line)
        if sw <= MAX_STROKE and (sw <= NARROW_STROKE
                                 or sw / max(1, chain_cells) <= MAX_STROKE_RATIO):
            ok.append({"cells": cs, "line": line, "chain": chain_cells,
                       "kind": k, "stroke": sw})
            return True
        return False

    for cs in comps:
        line, chain_cells = centreline(cs)
        k = classify(cs, line, chain_cells) if len(line) >= 2 else "fragment"
        kinds[k] = kinds.get(k, 0) + len(cs)
        consider(cs)
    lit = sum(len(c) for c in comps)
    print(f"{len(comps)} components, {lit} lit cells")
    for k in ("helix", "strand", "turn", "loop", "fragment"):
        print(f"   {k:9s} {kinds.get(k, 0):5d} cells  {kinds.get(k, 0) / lit:5.1%}")
    # Assign periods shortest-chain first, so each structure gets the prime
    # nearest its own ideal and the light keeps the same speed on all of them.
    ok = load_groups(ok)
    chosen = sorted(ok, key=lambda e: e["chain"])
    n = len(chosen)
    print(f"animating {n} structures = "
          f"{sum(len(e['cells']) for e in chosen) / lit:.0%} of the lit area")

    os.makedirs(OUTDIR, exist_ok=True)
    for f in os.listdir(OUTDIR):
        os.remove(os.path.join(OUTDIR, f))

    parts = [HEAD.format(seed=args.seed, ncomp=len(comps), n=n, sw=SW, sh=SH)]
    total = 0
    for i, e in enumerate(chosen):
        cs, line, chain_cells = e["cells"], e["line"], e["chain"]
        kind, sw_cells = e["kind"], e["stroke"]
        name = f"s{i}"
        w, h, r0, c0 = silhouette(cs, im, ox, oy, os.path.join(OUTDIR, name + ".png"))
        silhouette(cs, deep, ox, oy, os.path.join(OUTDIR, name + "-deep.png"))
        total += os.path.getsize(os.path.join(OUTDIR, name + ".png"))
        # Period from chain length, so every trace travels at the same speed.
        want = chain_cells / CELLS_PER_SEC / DRAW_FRACTION
        # Nearest prime, and repeats are allowed. Forcing 36 distinct periods
        # pushed the long chains up to 170s — three minutes between showings,
        # and the light crawling at 4.9 cells/s instead of 7.5. Two structures
        # sharing a period is invisible anyway: their phases differ.
        period = min(PRIMES, key=lambda q: (abs(q - want), q))
        d = "M" + "L".join(
            f"{(x - c0) * PITCH + PITCH // 2:.0f} {(y - r0) * PITCH + PITCH // 2:.0f}"
            for x, y in line)
        parts.append(SVG.format(
            i=i, name=name, w=w * PITCH, h=h * PITCH,
            x=(ox + c0 * PITCH) / SW * 100, y=(oy + r0 * PITCH) / SH * 100,
            pw=w * PITCH / SW * 100, ph=h * PITCH / SH * 100,
            d=period, dl=rng.randrange(period), chain=d,
            sw=round(sw_cells * PITCH)))
        print(f"  {name:4s} {kind:7s} {len(cs):4d} cells  chain {chain_cells:3d}  "
              f"stroke {sw_cells:4.1f}c  period {period:3d}s  "
              f"draw {period * DRAW_FRACTION:4.1f}s  "
              f"({chain_cells / (period * DRAW_FRACTION):4.1f} cells/s)")
    parts.append("\n</div>\n")
    open(PARTIAL, "w").write("".join(parts))
    print(f"wrote {PARTIAL} ({len(''.join(parts))} bytes) "
          f"+ {n} silhouettes ({total} bytes)")


if __name__ == "__main__":
    main()
